# config.yaml
path: C:\Users\006\PycharmProjects\pythonProject2 # Путь к папке с вашим датасетом
train: C:\Users\006\PycharmProjects\pythonProject2\dataset\images # Путь к папке с тренировочными изображениями
val: C:\Users\006\PycharmProjects\pythonProject2\dataset\images #  # Путь к папке с валидационными изображениями
nc: 2 # Укажите количество классов в вашем датасете
names: ['Roki2', 'Walker'] # Список с названиями классов